### ISSUE TITLE
v.0.1.1 not work on Win 8.1

### ISSUE THREAD

**Issue by Explorare** [mikkkee/gifer#4]
System: Windows 8.1 Enterprise x64
No process was created after excuse the win64 executable file.

**Comment by mikkkee** [comment]
Try win32 version? I think win32 will work. I'll look into it when I have time.

**Comment by Explorare** [comment]
Tried win32 version but still didn't work. 2 processes were created, and my firewall noticed me for the new connection established. But no GUI shown up. No error output debug using VS2015.

**Comment by mikkkee** [comment]
T_T have you tried to run from source directly?

**Comment by Explorare** [comment]
Yep. 2 processes were created, firewall noticed me for the new connection established, but no GUI shown up. No error output debug using VS2015.

**Comment by mikkkee** [comment]
Wierd, it'll take some time for me to make it work. At the mean time you may want to try the [electron version](https://github.com/mikkkee/gifer-electron). I think it's nicer. It has no packaged executables. Hence you have to run from the source ( as simple as `npm install && npm start ` ).

**Comment by Explorare** [comment]
My system has upgraded to Windows 10 14393.693 recently. But it still won't work. No process was created.

**Comment by mikkkee** [comment]
Hi, found the bug. It's because the old version never checks whether `moviepy` is valid or not (when `imageio` cannot find `ffmpeg`, `moviepy` cannot be used).

I just updated a new release ( https://github.com/mikkkee/gifer/releases/tag/v0.2 ). It should  fix this problem.

Thanks!
